package com.example.sol_denka_stockmanagement.state

data class ErrorState(
    val placeError: Boolean = false,
    val shippingOrderError: Boolean = false,
    val instructionNoError: Boolean = false,
    val rfidNumberError: Boolean = false,
    val expectedQtyError: Boolean = false,
    val operatorNameError: Boolean = false,
    val setCountError: Boolean = false,
    val setTireRfidNoError: Boolean = false,
    val setTpmsError: Boolean = false,
    val tpmsFormatError: Boolean = false,
    val tpmsDuplicateError: Boolean = false,
    val tireRfidFormatError: Boolean = false,
    val tireRfidNotInMasterError: Boolean = false,
    val tireRfidDuplicateError: Boolean = false,
    val secondUsageError: Boolean = false,
    val usageError: Boolean = false,
    val containerNoError: Boolean = false,
    val locationError: Boolean = false,
    val currentLocationTypeError: Boolean = false,
    val raceLotError: Boolean = false,
    val testLotError: Boolean = false,
    val beadMarkError: Boolean = false,
    val eventVenueError: Boolean = false,
    val tireTypeError: Boolean = false,
    val qualityAssuranceLotError: Boolean = false,
    val serialIpcError: Boolean = false,
    val rfidNoError: Boolean = false,
    val mountNoError: Boolean = false,
)
